# Generated by Django 4.2.7 on 2023-11-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_featuredimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featuredImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productimage'),
        ),
    ]
