# Generated by Django 4.2.7 on 2023-11-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_customer_order_profile_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='payer_id',
            field=models.CharField(default='asdsadasdasd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='sadasdasdasdasd', max_length=255),
            preserve_default=False,
        ),
    ]
